### ISSUE TITLE
python2 error due to super() call

### ISSUE THREAD

**Issue by kamdh** [sebp/scikit-learn-mpi-grid-search#1]
Fixed it by making MPIBatchWorker inherit from object

> class MPIBatchWorker(object)

along with the fixes in each class
`super(MPISlave,self)`
`super(MPIGridSearchCVMaster,self)`
However, this might break python 3 compatibility

**Comment by sebp** [comment]
Could you please file a pull request with the changes applied?

**Comment by sebp** [comment]
Fixed in commit 14d6508
